name: Fuzz

on:
  schedule:
    - cron: "41 4 * * 6"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  keyslot-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-fuzz
      - uses: Swatinem/rust-cache@v2
      - run: cargo fuzz run keyslots -- -max_total_time=60
